### ISSUE TITLE
ValidMethodOK Test Failed

### ISSUE THREAD

**Issue by Frizzle15** [No3Mc/PMAD-Phone-Selling-Store#99]
﻿ ValidMethodOK
   Source: tstPhone.cs line 33
   Duration: 4 ms

  Message: 
Assert.AreEqual failed. Expected:<There were the following errors : The Display Size can't be more than 5 charactersDate added is not valid. >. Actual:<>. 

  Stack Trace: 
tstPhone.ValidMethodOK() line 39

Unsure of how to fix this

**Comment by No3Mc** [comment]
Fixed in #112 @Frizzle15 
Problem was the conversion
